name: "🌟 Feature Request"
description: "Suggest a new feature or improvement for HydroServer"
body:
  - type: markdown
    attributes:
      value: |
        ## Before You Start...

        Thanks for taking the time to suggest a feature! Please first search for your feature request to see if it has been raised before.

        If you find that an existing feature request describes your needs, please join the existing discussion there.

        Otherwise, proceed to fill out this form to provide details about your feature request.

  - type: textarea
    id: problem-description
    attributes:
      label: "What problem are you trying to solve?"
      description: "Please give us a detailed explanation of the problem for which you are suggesting this feature."
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A detailed description of what you want to happen."
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: "Have you considered any alternatives?"
      description: "Are there alternative solutions or features you've considered? Why wouldn't they work?"

  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
