name: "Bug Report"
description: Create a report to help us improve HydroServer
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        Try to search for your issue - it may have already been answered or even fixed in the development branch.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: e.g. some background/context of how you ran into this bug.
