name: "Feature Request"
body:
  - type: textarea
    id: problem-description
    attributes:
      label: "Describe the feature you'd like and what it will do"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: "Why is this feature important?"
      description: "A short description of the importance of this feature and what it will help you achieve."
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]."
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: Add any other context about the feature request here.
