version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: hydroserver_reverse_proxy
    ports:
      - "3030:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
